// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Args struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Args) Reset()         { *m = Args{} }
func (m *Args) String() string { return proto.CompactTextString(m) }
func (*Args) ProtoMessage()    {}
func (*Args) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *Args) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Args.Unmarshal(m, b)
}
func (m *Args) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Args.Marshal(b, m, deterministic)
}
func (m *Args) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Args.Merge(m, src)
}
func (m *Args) XXX_Size() int {
	return xxx_messageInfo_Args.Size(m)
}
func (m *Args) XXX_DiscardUnknown() {
	xxx_messageInfo_Args.DiscardUnknown(m)
}

var xxx_messageInfo_Args proto.InternalMessageInfo

func (m *Args) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Args) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type Node struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	//    string group = 3; // 组
	//    string rpc = 4; // rpc 端口
	Peers                map[string]string `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Start                int64             `protobuf:"varint,6,opt,name=start,proto3" json:"start,omitempty"`
	Hwmd5                string            `protobuf:"bytes,7,opt,name=hwmd5,proto3" json:"hwmd5,omitempty"`
	Now                  int64             `protobuf:"varint,8,opt,name=now,proto3" json:"now,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *Node) GetPeers() map[string]string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *Node) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Node) GetHwmd5() string {
	if m != nil {
		return m.Hwmd5
	}
	return ""
}

func (m *Node) GetNow() int64 {
	if m != nil {
		return m.Now
	}
	return 0
}

type Request struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Date                 int64    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Verify               []byte   `protobuf:"bytes,4,opt,name=verify,proto3" json:"verify,omitempty"`
	Uuid                 string   `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Lease                int64    `protobuf:"varint,6,opt,name=lease,proto3" json:"lease,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Request) GetVerify() []byte {
	if m != nil {
		return m.Verify
	}
	return nil
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Request) GetLease() int64 {
	if m != nil {
		return m.Lease
	}
	return 0
}

type Data struct {
	Auth                 []byte   `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Lease                int64    `protobuf:"varint,2,opt,name=lease,proto3" json:"lease,omitempty"`
	Cipher               []byte   `protobuf:"bytes,3,opt,name=cipher,proto3" json:"cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *Data) GetLease() int64 {
	if m != nil {
		return m.Lease
	}
	return 0
}

func (m *Data) GetCipher() []byte {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Args)(nil), "proto.Args")
	proto.RegisterType((*Node)(nil), "proto.Node")
	proto.RegisterMapType((map[string]string)(nil), "proto.Node.PeersEntry")
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Data)(nil), "proto.Data")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xd5, 0x6e, 0x76, 0xf3, 0x31, 0x89, 0x0a, 0xb2, 0x50, 0x65, 0xe5, 0x42, 0xb4, 0x17, 0x22,
	0xa8, 0x72, 0x08, 0x42, 0xaa, 0xb8, 0x55, 0x02, 0x09, 0x09, 0xc4, 0x87, 0xf9, 0x05, 0xa6, 0x9e,
	0x74, 0x57, 0x34, 0x6b, 0x63, 0x7b, 0x5b, 0x85, 0x1b, 0x3f, 0x80, 0x7f, 0xc7, 0x0f, 0x42, 0x33,
	0x76, 0x68, 0x6f, 0xf4, 0xb4, 0xef, 0xd9, 0xf3, 0xde, 0x3c, 0xcf, 0x2c, 0x40, 0x6f, 0x0d, 0x6e,
	0x9c, 0xb7, 0xd1, 0x8a, 0x9a, 0x3f, 0xcd, 0x06, 0xaa, 0x0b, 0x7f, 0x15, 0x84, 0x80, 0xaa, 0xd7,
	0x7b, 0x94, 0xc5, 0xaa, 0x58, 0xcf, 0x14, 0x63, 0x3a, 0xd3, 0xc6, 0x78, 0x59, 0xa6, 0x33, 0xc2,
	0xcd, 0x9f, 0x02, 0xaa, 0x8f, 0xd6, 0xe0, 0x43, 0x05, 0xe2, 0x0c, 0x6a, 0x87, 0xe8, 0x83, 0xac,
	0x57, 0xa3, 0xf5, 0x7c, 0x7b, 0x9a, 0xda, 0x6f, 0xc8, 0x63, 0xf3, 0x99, 0x2e, 0xde, 0xf6, 0xd1,
	0x1f, 0x54, 0x2a, 0x12, 0x4f, 0xa0, 0x0e, 0x51, 0xfb, 0x28, 0xc7, 0xab, 0x62, 0x3d, 0x52, 0x89,
	0xd0, 0x69, 0x7b, 0xbb, 0x37, 0xaf, 0xe4, 0x84, 0x8d, 0x13, 0x11, 0x8f, 0x61, 0xd4, 0xdb, 0x5b,
	0x39, 0xe5, 0x4a, 0x82, 0xcb, 0x73, 0x80, 0x3b, 0x4b, 0xba, 0xff, 0x8e, 0x87, 0x1c, 0x90, 0x20,
	0xf9, 0xdc, 0xe8, 0xeb, 0x01, 0x73, 0xc0, 0x44, 0x5e, 0x97, 0xe7, 0x45, 0xf3, 0xab, 0x80, 0x89,
	0xc2, 0x1f, 0x03, 0x86, 0x48, 0x3a, 0xed, 0xdc, 0x51, 0xa7, 0x9d, 0x13, 0x27, 0x50, 0x76, 0x26,
	0x8b, 0xca, 0xce, 0xd0, 0x3b, 0x8d, 0x8e, 0x28, 0x47, 0xdc, 0x9a, 0xb1, 0x38, 0x85, 0xf1, 0x0d,
	0xfa, 0x6e, 0x77, 0x90, 0xd5, 0xaa, 0x58, 0x2f, 0x54, 0x66, 0x54, 0x3b, 0x0c, 0x9d, 0x91, 0x75,
	0x9a, 0x09, 0x61, 0xca, 0x71, 0x8d, 0x3a, 0xe0, 0xf1, 0x95, 0x4c, 0x9a, 0x77, 0x50, 0xbd, 0xd1,
	0x51, 0xf3, 0x14, 0x87, 0xd8, 0x72, 0x80, 0x85, 0x62, 0x7c, 0xa7, 0x28, 0xef, 0x29, 0xa8, 0xe7,
	0x65, 0xe7, 0x5a, 0xf4, 0x9c, 0x64, 0xa1, 0x32, 0x6b, 0xbe, 0xc0, 0x54, 0x61, 0x70, 0xb6, 0x0f,
	0xbc, 0x93, 0x4b, 0x6b, 0xd2, 0x9e, 0x6a, 0xc5, 0x58, 0x3c, 0xe5, 0xfc, 0x9a, 0xcd, 0xe6, 0xdb,
	0x79, 0x5e, 0x09, 0x35, 0xe7, 0xc7, 0x68, 0x1a, 0xc1, 0x3e, 0x5c, 0xb1, 0xeb, 0x4c, 0x11, 0xdc,
	0x9e, 0xc1, 0xf8, 0x6b, 0xd4, 0x11, 0xbd, 0x68, 0x12, 0x1a, 0x82, 0x38, 0x0a, 0xe9, 0x07, 0x5a,
	0xce, 0xef, 0x2d, 0x76, 0xfb, 0xbb, 0x80, 0xd9, 0xc5, 0x10, 0x5b, 0xeb, 0xbb, 0x9f, 0x28, 0x9e,
	0x41, 0x45, 0x44, 0x9c, 0xe4, 0x92, 0x3c, 0xe8, 0xe5, 0xa3, 0x7f, 0x3c, 0x67, 0x7d, 0x01, 0xd3,
	0xf7, 0x88, 0xee, 0x43, 0xd7, 0xe3, 0xff, 0x8b, 0x9f, 0xc3, 0xe4, 0xd3, 0x6e, 0xf7, 0xa0, 0xda,
	0x6f, 0x63, 0xe6, 0x2f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x83, 0x26, 0x0e, 0x0b, 0x01, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StaterClient is the client API for Stater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StaterClient interface {
	Status(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Node, error)
}

type staterClient struct {
	cc *grpc.ClientConn
}

func NewStaterClient(cc *grpc.ClientConn) StaterClient {
	return &staterClient{cc}
}

func (c *staterClient) Status(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/proto.Stater/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaterServer is the server API for Stater service.
type StaterServer interface {
	Status(context.Context, *Args) (*Node, error)
}

func RegisterStaterServer(s *grpc.Server, srv StaterServer) {
	s.RegisterService(&_Stater_serviceDesc, srv)
}

func _Stater_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Args)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaterServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Stater/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaterServer).Status(ctx, req.(*Args))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stater_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Stater",
	HandlerType: (*StaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Stater_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}

// AuthorizeClient is the client API for Authorize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorizeClient interface {
	Auth(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	KeepLine(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	OffLine(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type authorizeClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizeClient(cc *grpc.ClientConn) AuthorizeClient {
	return &authorizeClient{cc}
}

func (c *authorizeClient) Auth(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Authorize/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) KeepLine(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Authorize/KeepLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizeClient) OffLine(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Authorize/OffLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizeServer is the server API for Authorize service.
type AuthorizeServer interface {
	Auth(context.Context, *Request) (*Response, error)
	KeepLine(context.Context, *Request) (*Response, error)
	OffLine(context.Context, *Request) (*Response, error)
}

func RegisterAuthorizeServer(s *grpc.Server, srv AuthorizeServer) {
	s.RegisterService(&_Authorize_serviceDesc, srv)
}

func _Authorize_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Authorize/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).Auth(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_KeepLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).KeepLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Authorize/KeepLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).KeepLine(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authorize_OffLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizeServer).OffLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Authorize/OffLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizeServer).OffLine(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authorize_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Authorize",
	HandlerType: (*AuthorizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Authorize_Auth_Handler,
		},
		{
			MethodName: "KeepLine",
			Handler:    _Authorize_KeepLine_Handler,
		},
		{
			MethodName: "OffLine",
			Handler:    _Authorize_OffLine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}
